server:
  port: 8097
  servlet:
    session:
      timeout: 10m
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    tomcat:
      initial-size: 0
      max-idle: 20
      max-wait: 60000
      min-idle: 1
    url: jdbc:mysql://127.0.0.1:3306/stu?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: admin
      
 

    
