server:
  port: 8180
  servlet:
    context-path: /
    session:
      timeout: 10m
  tomcat:
    uri-encoding: UTF-8
    
    
spring:

  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:D:/h2/test
    username: sa
    
  jackson:
    serialization:
      INDENT_OUTPUT: true
      
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  jwt:     
    header: Authorization
    secret: YXV0aG9yaXR5LWtleS1zcHJpbmctc2VjdXJpdHktbXktc2lnbml0dXJlCg==
    #authority-key-spring-security-my-signiture 256 bits
    validity-in-seconds: 86400
    validity-in-seconds-for-remember-me: 10800
    route:
      authentication:
        path: auth
        refresh: refresh
        
        


  